blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/dennisdoomen/packageguard?tab=readme-ov-file#how-do-i-configure-it
    about: Read our comprehensive documentation.
  - name: â­ Sponsor PackageGuard
    url: https://github.com/sponsors/dennisdoomen
    about: Help the continued development.
  - name: ğŸ’¬ Ask on Stack Overflow
    url: https://stackoverflow.com/questions/tagged/PackageGuard
    about: The best place for asking general purpose questions.
  - name: ğŸ’¬ Ask on BlueSky
    url: https://bsky.app/profile/dennisdoomen.com
    about: Get in touch with the author on Bluesky
  - name: ğŸ’¬ Ask on Twitter/X
    url: https://x.com/ddoomen
    about: Get in touch with the author on Twitter/X
